// <auto-generated />
namespace EPM.Wallet.Data.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V7));
        
        string IMigrationMetadata.Id
        {
            get { return "201703020952526_V7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
